const { v4: uuidv4 } = require("uuid");

const categories = [
  {
    id: uuidv4(),
    name: "General Knowledge",
  },
  {
    id: uuidv4(),
    name: "History",
  },
  {
    id: uuidv4(),
    name: "Geography",
  },
];

const difficulties = [
  {
    id: uuidv4(),
    name: "easy",
  },
  {
    id: uuidv4(),
    name: "medium",
  },
  {
    id: uuidv4(),
    name: "hard",
  },
];

const questions = [
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question:
      "What machine element is located in the center of fidget spinners?",
    correctAnswer: "Bearings",
    incorrectAnswers: ["Axles", "Gears", "Belts"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question:
      "What is on display in the Madame Tussaud&#039;s museum in London?",
    correctAnswer: "Wax sculptures",
    incorrectAnswers: [
      "Designer clothing",
      "Unreleased film reels",
      "Vintage cars",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question: "When someone is inexperienced they are said to be what color?",
    correctAnswer: "Green",
    incorrectAnswers: ["Red", "Blue", "Yellow"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question:
      "What kind of aircraft was developed by Igor Sikorsky in the United States in 1942?",
    correctAnswer: "Helicopter",
    incorrectAnswers: ["Stealth Blimp", "Jet", "Space Capsule"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question: "What is Cynophobia the fear of?",
    correctAnswer: "Dogs",
    incorrectAnswers: ["Birds", "Flying", "Germs"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question: "Which one of the following rhythm games was made by Harmonix?",
    correctAnswer: "Rock Band",
    incorrectAnswers: [
      "Meat Beat Mania",
      "Guitar Hero Live",
      "Dance Dance Revolution",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question:
      "What type of animal was Harambe, who was shot after a child fell into it&#039;s enclosure at the Cincinnati Zoo?",
    correctAnswer: "Gorilla",
    incorrectAnswers: ["Tiger", "Panda", "Crocodile"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question: "What do the letters in the GMT time zone stand for?",
    correctAnswer: "Greenwich Mean Time",
    incorrectAnswers: [
      "Global Meridian Time",
      "General Median Time",
      "Glasgow Man Time",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question:
      "Which of the following card games revolves around numbers and basic math?",
    correctAnswer: "Uno",
    incorrectAnswers: ["Go Fish", "Twister", "Munchkin"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question: "Which of these Marvel games was released on the Playstation 2?",
    correctAnswer: "Spider-Man 2",
    incorrectAnswers: [
      "Silver Surfer",
      "Howard the Duck",
      "Wolverine: Adamantium Rage",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question: "What is the Spanish word for &quot;donkey&quot;?",
    correctAnswer: "Burro",
    incorrectAnswers: ["Caballo", "Toro", "Perro"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question: "What alcoholic drink is made from molasses?",
    correctAnswer: "Rum",
    incorrectAnswers: ["Gin", "Vodka", "Whisky"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question: "Who is the author of Jurrasic Park?",
    correctAnswer: "Michael Crichton",
    incorrectAnswers: ["Peter Benchley", "Chuck Paluhniuk", "Irvine Welsh"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question: "How many colors are there in a rainbow?",
    correctAnswer: "7",
    incorrectAnswers: ["8", "9", "10"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question: "What is the French word for &quot;hat&quot;?",
    correctAnswer: "Chapeau",
    incorrectAnswers: ["Bonnet", " &Eacute;charpe", " Casque"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question:
      "The drug cartel run by Pablo Escobar originated in which South American city?",
    correctAnswer: "Medell&iacute;n",
    incorrectAnswers: ["Bogot&aacute;", "Quito", "Cali"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question:
      "What was the name of the WWF professional wrestling tag team made up of the wrestlers Ax and Smash?",
    correctAnswer: "Demolition",
    incorrectAnswers: [
      "The Dream Team",
      "The Bushwhackers",
      "The British Bulldogs",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question: "Which of the following is not the host of a program on NPR?",
    correctAnswer: "Ben Shapiro",
    incorrectAnswers: ["Terry Gross", "Ira Glass", "Peter Sagal"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question: "What is Tasmania?",
    correctAnswer: "An Australian State",
    incorrectAnswers: [
      "A flavor of Ben and Jerry&#039;s ice-cream",
      "A Psychological Disorder",
      "The Name of a Warner Brothers Cartoon Character",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[0].id,
    question:
      "Foie gras is a French delicacy typically made from what part of a duck or goose?",
    correctAnswer: "Liver",
    incorrectAnswers: ["Heart", "Stomach", "Intestines"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question:
      "Which of the following buildings is example of a structure primarily built in the Art Deco architectural style?",
    correctAnswer: "Niagara Mohawk Building",
    incorrectAnswers: ["Taipei 101", "One Detroit Center", "Westendstrasse 1"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question: "In the Morse code, which letter is indicated by 3 dots? ",
    correctAnswer: "S",
    incorrectAnswers: ["O", "A", "C"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question:
      "According to the BBPA, what is the most common pub name in the UK?",
    correctAnswer: "Red Lion",
    incorrectAnswers: ["Royal Oak", "White Hart", "King&#039;s Head"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question: "What is the romanized Japanese word for &quot;university&quot;?",
    correctAnswer: "Daigaku",
    incorrectAnswers: ["Toshokan", "Jimusho", "Shokudou"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question: "Rolex is a company that specializes in what type of product?",
    correctAnswer: "Watches",
    incorrectAnswers: ["Cars", "Computers", "Sports equipment"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question: "Which river flows through the Scottish city of Glasgow?",
    correctAnswer: "Clyde",
    incorrectAnswers: ["Tay", "Dee", "Tweed"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question:
      "Which slogan did the fast food company, McDonald&#039;s, use before their &quot;I&#039;m Lovin&#039; It&quot; slogan?",
    correctAnswer: "We Love to See You Smile",
    incorrectAnswers: [
      "Why Pay More!?",
      "Have It Your Way",
      "Making People Happy Through Food",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question: "What is the world&#039;s most expensive spice by weight?",
    correctAnswer: "Saffron",
    incorrectAnswers: ["Cinnamon", "Cardamom", "Vanilla"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question: "What is the romanized Russian word for &quot;winter&quot;?",
    correctAnswer: "Zima",
    incorrectAnswers: ["Leto", "Vesna", "Osen&#039;"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question:
      "Which of these is the name of a Japanese system of alternative medicine, literally meaning &quot;finger pressure&quot;?",
    correctAnswer: "Shiatsu",
    incorrectAnswers: ["Ukiyo", "Majime", "Ikigai"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question: "The term &quot;scientist&quot; was coined in which year?",
    correctAnswer: "1833",
    incorrectAnswers: ["1933", "1942", "1796"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question:
      "Which American manufactured submachine gun was informally known by the American soldiers that used it as &quot;Grease Gun&quot;?",
    correctAnswer: "M3",
    incorrectAnswers: ["Colt 9mm", "Thompson", "MAC-10"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question: "A statue of Charles Darwin sits in what London museum?",
    correctAnswer: "Natural History Museum",
    incorrectAnswers: ["Tate", "British Museum", "Science Museum"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question:
      "Frank Lloyd Wright was the architect behind what famous building?",
    correctAnswer: "The Guggenheim",
    incorrectAnswers: [
      "Villa Savoye",
      "Sydney Opera House",
      "The Space Needle",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question: "What is a &quot;dakimakura&quot;?",
    correctAnswer: "A body pillow",
    incorrectAnswers: [
      "A Chinese meal, essentially composed of fish",
      "A yoga posture",
      "A word used to describe two people who truly love each other",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question: "What is the Portuguese word for &quot;Brazil&quot;?",
    correctAnswer: "Brasil",
    incorrectAnswers: ["Brazil", "Brasilia", "Bras&iacute;l"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question:
      "Which item of clothing is usually worn by a Scotsman at a wedding?",
    correctAnswer: "Kilt",
    incorrectAnswers: ["Skirt", "Dress", "Rhobes"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question:
      "Which of the following Ivy League universities has its official motto in Hebrew as well as in Latin?",
    correctAnswer: "Yale University",
    incorrectAnswers: [
      "Princeton University",
      "Harvard University",
      "Columbia University",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question: "Earl Grey tea is black tea flavoured with what?",
    correctAnswer: "Bergamot oil",
    incorrectAnswers: ["Lavender", "Vanilla", "Honey"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[0].id,
    question: "What fast food chain has the most locations globally? ",
    correctAnswer: "Subway",
    incorrectAnswers: ["Starbucks", "McDonalds", "KFC"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question:
      "In &quot;Resident Evil 3&quot;, how many inventory slots does Jill have at the start of the game?",
    correctAnswer: "10",
    incorrectAnswers: ["6", "8", "12"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question: "What is the romanized Arabic word for &quot;moon&quot;?",
    correctAnswer: "Qamar",
    incorrectAnswers: ["Najma", "Kawkab", "Shams"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question:
      "Virtual reality company Oculus VR lost which of it&#039;s co-founders in a freak car accident in 2013?",
    correctAnswer: "Andrew Scott Reisse",
    incorrectAnswers: ["Nate Mitchell", "Jack McCauley", "Palmer Luckey"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question:
      "Originally another word for poppy, coquelicot is a shade of what?",
    correctAnswer: "Red",
    incorrectAnswers: ["Green", "Blue", "Pink"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question: "Chartreuse is a color between yellow and what?",
    correctAnswer: "Green",
    incorrectAnswers: ["Red", "Black", "Purple"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question: "Sciophobia is the fear of what?",
    correctAnswer: "Shadows",
    incorrectAnswers: ["Eating", "Bright lights", "Transportation"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question: "Who founded the Khan Academy?",
    correctAnswer: "Sal Khan",
    incorrectAnswers: ["Ben Khan", "Kitt Khan", "Adel Khan"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question: "Nephelococcygia is the practice of doing what?",
    correctAnswer: "Finding shapes in clouds",
    incorrectAnswers: [
      "Sleeping with your eyes open",
      "Breaking glass with your voice",
      "Swimming in freezing water",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question: "What is the airspeed velocity of an unladen swallow?",
    correctAnswer: "24 MPH",
    incorrectAnswers: ["15 MPH", "20 MPH", "200 MPH"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question:
      "Located in Chile, El Teniente is the world&#039;s largest underground mine for what metal?",
    correctAnswer: "Copper",
    incorrectAnswers: ["Iron", "Nickel", "Silver"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question:
      "Which of the following is an existing family in &quot;The Sims&quot;?",
    correctAnswer: "The Goth Family",
    incorrectAnswers: ["The Family", "The Simoleon Family", "The Proud Family"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question:
      "What type of dog is &#039;Handsome Dan&#039;, the mascot of Yale University?",
    correctAnswer: "Bulldog",
    incorrectAnswers: ["Yorkshire Terrier", "Boxer", "Pug"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question:
      "Which product did Nokia, the telecommunications company, originally sell?",
    correctAnswer: "Paper",
    incorrectAnswers: ["Phones", "Computers", "Processors"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question:
      "The words &quot;bungalow&quot; and &quot;shampoo&quot; originate from the languages of which country?",
    correctAnswer: "India",
    incorrectAnswers: ["Papua New Guinea", "Ethiopia", "China"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question: "How many notes are there on a standard grand piano?",
    correctAnswer: "88",
    incorrectAnswers: ["98", "108", "78"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question:
      "Electronic music producer Kygo&#039;s popularity skyrocketed after a certain remix. Which song did he remix?",
    correctAnswer: "Ed Sheeran - I See Fire",
    incorrectAnswers: [
      "Marvin Gaye - Sexual Healing",
      "Coldplay - Midnight",
      "a-ha - Take On Me",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question:
      "According to the 2014-2015 Australian Bureau of Statistics, what percentage of Australians were born overseas?",
    correctAnswer: "28%",
    incorrectAnswers: ["13%", "20%", "7%"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question: "The Swedish word &quot;Grunka&quot; means what in English?",
    correctAnswer: "Thing",
    incorrectAnswers: ["People", "Place", "Pineapple"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question: "Where is Apple Inc. headquartered?",
    correctAnswer: "Cupertino, California",
    incorrectAnswers: [
      "Redwood City, California",
      "Redmond, Washington",
      "Santa Monica, CA",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[0].id,
    question:
      "Which musician has collaborated with American producer Porter Robinson and released the 2016 song &quot;Shelter&quot;?",
    correctAnswer: "Madeon",
    incorrectAnswers: ["Mat Zo", "deadmau5", "Zedd"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "What was the first sport to have been played on the moon?",
    correctAnswer: "Golf",
    incorrectAnswers: ["Football", "Tennis", "Soccer"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "In which year did the Invasion of Kuwait by Iraq occur?",
    correctAnswer: "1990",
    incorrectAnswers: ["1992", "1988", "1986"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question:
      "The original Roman alphabet lacked the following letters EXCEPT:",
    correctAnswer: "X",
    incorrectAnswers: ["W", "U", "J"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "What is the historical name of Sri Lanka?",
    correctAnswer: "Ceylon",
    incorrectAnswers: ["Myanmar", "Colombo", "Badulla"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question:
      "Which of the following countries was not an axis power during World War II?",
    correctAnswer: " Soviet Union",
    incorrectAnswers: ["Italy", "Germany", "Japan"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question:
      "These two countries held a commonwealth from the 16th to 18th century.",
    correctAnswer: "Poland and Lithuania",
    incorrectAnswers: [
      "Hutu and Rwanda",
      "North Korea and South Korea",
      "Bangladesh and Bhutan",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question:
      "During WWII, in 1945, the United States dropped atomic bombs on the two Japanese cities of Hiroshima and what other city?",
    correctAnswer: "Nagasaki",
    incorrectAnswers: ["Kawasaki", "Tokyo", "Kagoshima"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question:
      "What was the name commonly given to the ancient trade routes that connected the East and West of Eurasia?",
    correctAnswer: "Silk Road",
    incorrectAnswers: ["Spice Road", "Clay Road", "Salt Road"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "Who led the Communist Revolution of Russia?",
    correctAnswer: "Vladimir Lenin",
    incorrectAnswers: ["Joseph Stalin", "Vladimir Putin", "Mikhail Gorbachev"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "What country joined the EU in 2013?",
    correctAnswer: "Croatia",
    incorrectAnswers: ["Bulgaria", "Slovenia", "Turkey"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "When was Google founded?",
    correctAnswer: "September 4, 1998",
    incorrectAnswers: [
      "October 9, 1997",
      "December 12, 1989",
      "Feburary 7th, 2000",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "In 1453, which important city fell?",
    correctAnswer: "Constantinople",
    incorrectAnswers: ["Rome", "Hamburg", "Athens"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question:
      "Which one of these tanks was designed and operated by the United Kingdom?",
    correctAnswer: "Tog II",
    incorrectAnswers: ["M4 Sherman", "Tiger H1", "T-34"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "Which of the following was Brazil was a former colony under?",
    correctAnswer: "Portugal",
    incorrectAnswers: ["Spain", "The Netherlands", "France"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "Who was the first president of the United States?",
    correctAnswer: "George Washington",
    incorrectAnswers: ["James Madison", "Thomas Jefferson", "James K. Polk"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "Who was the first prime minister of Canada?",
    correctAnswer: "John Macdonald",
    incorrectAnswers: ["John Abbott", "Alexander Mackenzie", "Robert Borden"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question:
      "In what year did the Great Northern War, between Russia and Sweden, end?",
    correctAnswer: "1721",
    incorrectAnswers: ["1726", "1727", "1724"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "In what year did the Wall Street Crash take place?",
    correctAnswer: "1929",
    incorrectAnswers: ["1932", "1930", "1925"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "The Ottoman Empire was dissolved after their loss in which war?",
    correctAnswer: "World War I",
    incorrectAnswers: [
      "Crimean War",
      "Serbian Revolution",
      "Second Balkan War",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[1].id,
    question: "The collapse of the Soviet Union took place in which year?",
    correctAnswer: "1991",
    incorrectAnswers: ["1992", "1891", "1990"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question: "Joseph Smith was the founder of what religion?",
    correctAnswer: "Mormonism",
    incorrectAnswers: ["Buddhism", "Christianity", "Hinduism"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question:
      "What is the name of the ship which was only a few miles away from the RMS Titanic when it struck an iceberg on April 14, 1912?",
    correctAnswer: "Californian",
    incorrectAnswers: ["Carpathia", "Cristol", "Commerce"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question:
      "The Herero genocide was perpetrated in Africa by which of the following colonial nations?",
    correctAnswer: "Germany",
    incorrectAnswers: ["Britain", "Belgium", "France"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question:
      "What year were the Marian Reforms instituted in the Roman Republic?",
    correctAnswer: "107 BCE",
    incorrectAnswers: ["42 BCE", "264 BCE", "102 CE"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question:
      "In the War of the Pacific (1879 - 1883), Bolivia lost its access to the Pacific Ocean after being defeated by which South American country?",
    correctAnswer: "Chile",
    incorrectAnswers: ["Peru", "Brazil", "Argentina"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question:
      "What is the name of the US Navy spy ship which was attacked and captured by North Korean forces in 1968?",
    correctAnswer: "USS Pueblo",
    incorrectAnswers: [
      "USS North Carolina",
      "USS Constitution",
      "USS Indianapolis",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question: "The seed drill was invented by which British inventor?",
    correctAnswer: "Jethro Tull",
    incorrectAnswers: ["Charles Babbage", "Isaac Newton", "J.J Thomson"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question:
      "In what year did Neil Armstrong and Buzz Aldrin land on the moon?",
    correctAnswer: "1969",
    incorrectAnswers: ["1965", "1966", "1973"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question: "What year did the Battle of Agincourt take place?",
    correctAnswer: "1415",
    incorrectAnswers: ["1463", "1401", "1422"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question: "What is the oldest US state?",
    correctAnswer: "Delaware",
    incorrectAnswers: ["Rhode Island", "Maine", "Virginia"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question: "Who assassinated Archduke Franz Ferdinand?",
    correctAnswer: "Gavrilo Princip",
    incorrectAnswers: [
      "Nedeljko Čabrinović",
      "Oskar Potiorek",
      "Ferdinand Cohen-Blind",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question: "When was the People&#039;s Republic of China founded?",
    correctAnswer: "October 1, 1949",
    incorrectAnswers: ["April 3, 1947", "May 7, 1945", "December 6, 1950"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question:
      "Who crowned Charlemagne as Holy Roman Emperor on Christmas Day in 800?",
    correctAnswer: "Pope Leo III",
    incorrectAnswers: ["Pope Urban IV", "Pope Stephen V", "Pope Valentine"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question:
      "What was the code name for the German invasion of the Soviet Union in WW2?",
    correctAnswer: "Operation Barbarossa",
    incorrectAnswers: [
      "Operation Kaiserschlact",
      "Operation Unthinkable",
      "Operation Molotov",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question: "What was the capital of South Vietnam before the Vietnam War?",
    correctAnswer: "Saigon",
    incorrectAnswers: ["Ho Chi Minh City", "Hanoi", "Hue"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question:
      "What was the transfer of disease, crops, and people across the Atlantic shortly after the discovery of the Americas called?",
    correctAnswer: "The Columbian Exchange",
    incorrectAnswers: [
      "Triangle Trade",
      "Transatlantic Slave Trade",
      "The Silk Road",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question: "What year did Australia become a federation?",
    correctAnswer: "1901",
    incorrectAnswers: ["1910", "1899", "1911"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question:
      "Who was the last Roman emperor in the Year of Four Emperors (69 AD)?",
    correctAnswer: "Vespasian",
    incorrectAnswers: ["Vitellius", "Otho", "Galba"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question: "Which of the following is NOT classified as a Semetic language?",
    correctAnswer: "Sumerian",
    incorrectAnswers: ["Maltese", "Akkadian", "Mandaic"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[1].id,
    question:
      "In what dialogue did Socrates defend himself to the court of Athens? ",
    correctAnswer: "The Apology",
    incorrectAnswers: ["The Euthyphro", "The Laws", "The Republic"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question:
      "With which Greek philosopher would you associate the phrase, &quot;I know that I know nothing&quot;?",
    correctAnswer: "Socrates",
    incorrectAnswers: ["Aristotle", "Plato", "Pythagoras"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question:
      "What was the code name for the Allied invasion of Southern France on August 15th, 1944?",
    correctAnswer: "Operation Dragoon",
    incorrectAnswers: [
      "Operation Overlord",
      "Operation Market Garden",
      "Operation Torch",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question: "What was found in 1946 by two young shepards near a cave?",
    correctAnswer: "Dead Sea Scrolls",
    incorrectAnswers: [
      "The Blackbeard Chest",
      "Sheep",
      "The First Oaxaca Cave Sleeper",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question:
      "When did Canada leave the confederation to become their own nation?",
    correctAnswer: "July 1st, 1867",
    incorrectAnswers: ["July 1st, 1763", "July 1st, 1832", "July 1st, 1902"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question: "Bohdan Khmelnytsky was which of the following?",
    correctAnswer: "Leader of the Ukrainian Cossacks",
    incorrectAnswers: [
      "General Secretary of the Communist Party of the USSR",
      "Prince of Wallachia",
      "Grand Prince of Novgorod",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question:
      "Which U.S. president was said to have been too honest to lie to his father about chopping down a cherry tree?",
    correctAnswer: "George Washington",
    incorrectAnswers: ["Abraham Lincoln", "Thomas Jefferson", "James Monroe"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question:
      "Which of the following was not one of Joseph Stalin&#039;s ten blows during World War II?",
    correctAnswer: "Vistula-Oder Offensive",
    incorrectAnswers: [
      "Crimean Offensive",
      "Leningrad-Novgorod Offensive",
      "Operation Bagration",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question: "The Battle of Hastings was fought in which year?",
    correctAnswer: "1066",
    incorrectAnswers: ["911", "1204", "1420"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question: "Which day did World War I begin?",
    correctAnswer: "July 28",
    incorrectAnswers: ["January 28", "June 28", "April 28"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question: "What age was King Henry V when he died?",
    correctAnswer: "35",
    incorrectAnswers: ["62", "87", "73"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question: "On which day did ARPANET suffer a 4 hour long network crash?",
    correctAnswer: "October 27, 1980",
    incorrectAnswers: [
      "November 21, 1969",
      "October 29, 1969",
      "December 9, 1991",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question:
      "What was the name of the German offensive operation in October 1941 to take Moscow before winter?",
    correctAnswer: "Operation Typhoon",
    incorrectAnswers: [
      "Operation Sunflower",
      "Operation Barbarossa",
      "Case Blue",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question:
      "Which of the following physicists did NOT work on the Manhattan project?",
    correctAnswer: "Murray Gell-Mann",
    incorrectAnswers: [
      "Richard Feynman",
      "J. Robert Oppenheimer",
      "John Von-Neumann",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question: "When did Lithuania declare independence from the Soviet Union?",
    correctAnswer: "March 11th, 1990",
    incorrectAnswers: [
      "December 25th, 1991",
      "December 5th, 1991",
      "April 20th, 1989",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question:
      "What year was the United States Declaration of Independence signed?",
    correctAnswer: "1776",
    incorrectAnswers: ["1775", "1774", "1777"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question: "List the following Iranic empires in chronological order:",
    correctAnswer: "Median, Achaemenid, Parthian, Sassanid",
    incorrectAnswers: [
      "Median, Achaemenid, Sassanid, Parthian",
      "Achaemenid, Median, Parthian, Sassanid",
      "Achaemenid, Median, Sassanid, Parthian",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question: "Which is the hull NO. of the Fletcher class destroyer Fletcher?",
    correctAnswer: "DD-445",
    incorrectAnswers: ["DD-992", "DD-444", "DD-446"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question: "The pantheon in Rome was used to worship what god?",
    correctAnswer: "Any god they wanted",
    incorrectAnswers: ["Athena", "Zeus", "Both Athena and Zeus"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question:
      "The ontological argument for the proof of God&#039;s existence is first attributed to whom?",
    correctAnswer: "Anselm of Canterbury",
    incorrectAnswers: ["Ren&eacute; Descartes", "Immanuel Kant", "Aristotle"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[1].id,
    question: "How many sonatas did Ludwig van Beethoven write?",
    correctAnswer: "32",
    incorrectAnswers: ["50", "31", "21"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "Greenland is a part of which kingdom?",
    correctAnswer: "Denmark",
    incorrectAnswers: ["Sweden", "Norway", "United Kingdom"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "What is the Polish city known to Germans as Danzig?",
    correctAnswer: "Gdańsk",
    incorrectAnswers: ["Warsaw", "Zakopane", "Poznań"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "What is the capital of the American state of Arizona?",
    correctAnswer: "Phoenix",
    incorrectAnswers: ["Montgomery", "Tallahassee", "Raleigh"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "Which of these is NOT an Australian state or territory?",
    correctAnswer: "Alberta",
    incorrectAnswers: ["New South Wales", "Victoria", "Queensland"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question:
      "All of the following are classified as Finno-Ugric languages EXCEPT:",
    correctAnswer: "Samoyedic",
    incorrectAnswers: ["Hungarian", "Finnish", "Estonian"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "What is the capital of Denmark?",
    correctAnswer: "Copenhagen",
    incorrectAnswers: ["Aarhus", "Odense", "Aalborg"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "What is the nickname for the US state Delaware?",
    correctAnswer: "The First State",
    incorrectAnswers: [
      "The Fiftieth State",
      "The Second State",
      "The Sixteenth State",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question:
      "Which of the following countries has a flag featuring a yellow lion wielding a sword on a dark red background?",
    correctAnswer: "Sri Lanka",
    incorrectAnswers: ["Kiribati", "Scotland", "Bhutan"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "Which UK country features a dragon on their flag?",
    correctAnswer: "Wales",
    incorrectAnswers: ["England", "North Ireland", "Scotland"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "What is the Capital of the United States?",
    correctAnswer: "Washington, D.C.",
    incorrectAnswers: ["Los Angelas, CA", "New York City, NY", "Houston, TX"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "What is the capital of Indonesia?",
    correctAnswer: "Jakarta",
    incorrectAnswers: ["Bandung", "Medan", "Palembang"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question:
      "Which of the following Arab countries does NOT have a flag containing only Pan-Arab colours?",
    correctAnswer: "Qatar",
    incorrectAnswers: ["Kuwait", "United Arab Emirates", "Jordan"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "Which Russian oblast forms a border with Poland?",
    correctAnswer: "Kaliningrad",
    incorrectAnswers: ["Samara", "Nizhny Novgorod", "Omsk"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "What country is the second largest in the world by area?",
    correctAnswer: "Canada",
    incorrectAnswers: ["Russia", "China", "United States of America"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "What is the name of New Zealand&#039;s indigenous people?",
    correctAnswer: "Maori",
    incorrectAnswers: ["Vikings", "Polynesians", "Samoans"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question: "How many federal states does Germany have?",
    correctAnswer: "16",
    incorrectAnswers: ["13", "32", "25"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question:
      "Which of these African countries list &quot;Spanish&quot; as an official language?",
    correctAnswer: "Equatorial Guinea",
    incorrectAnswers: ["Guinea", "Cameroon", "Angola"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question:
      "What is the only state in the United States that does not have a flag in a shape with 4 edges?",
    correctAnswer: "Ohio",
    incorrectAnswers: ["Florida", "Idaho", "New Mexico"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question:
      "What name was historically used for the Turkish city currently known as Istanbul?",
    correctAnswer: "Constantinople",
    incorrectAnswers: ["H&uuml;davendigar", "S&ouml;ğ&uuml;t", "Adrianople"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[0].id,
    categoryId: categories[2].id,
    question:
      "The longest shared border in the world can be found between which two nations?",
    correctAnswer: "Canada and the United States",
    incorrectAnswers: [
      "Chile and Argentina",
      "Russia and China",
      "India and Pakistan",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "What is the longest river in Europe?",
    correctAnswer: "Volga",
    incorrectAnswers: ["Danube", "Rhine", "Thames"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "Where is the &quot;Sonoran Desert&quot; located?",
    correctAnswer: "North America",
    incorrectAnswers: ["South America", "Asia", "Africa"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "How many countries are inside the United Kingdom?",
    correctAnswer: "Four",
    incorrectAnswers: ["Two", "Three", "One"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "Which country claims ownership of the disputed state Kosovo?",
    correctAnswer: "Serbia",
    incorrectAnswers: ["Croatia", "Albania", "Macedonia"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "Which country has the abbreviation &quot;CH&quot;?",
    correctAnswer: "Switzerland",
    incorrectAnswers: ["China", "Canada", "No Country"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "Where are the Nazca Lines located?",
    correctAnswer: "Peru",
    incorrectAnswers: ["Brazil", "Colombia", "Ecuador"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "What was the African nation of Zimbabwe formerly known as?",
    correctAnswer: "Rhodesia",
    incorrectAnswers: ["Zambia", "Mozambique", " Bulawayo"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "Kuala Lumpur is the capital of which country?",
    correctAnswer: "Malaysia",
    incorrectAnswers: ["Indonesia", "Singapore", "Thailand"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "What is the official national language of Pakistan?",
    correctAnswer: "Urdu",
    incorrectAnswers: ["Indian", "Punjabi", "Pashto"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question:
      "Colchester Overpass, otherwise known as &quot;Bunny Man Bridge&quot;, is located where?",
    correctAnswer: "Fairfax County, Virginia",
    incorrectAnswers: [
      "Medford, Oregon",
      "Braxton County, Virgina",
      "Lemon Grove, California",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "What is the capital of Slovakia?",
    correctAnswer: "Bratislava",
    incorrectAnswers: ["Sofia", "Ljubljana", "Sarajevo"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "How many countries are larger than Australia?",
    correctAnswer: "5",
    incorrectAnswers: ["4", "3", "6"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "What is the capital of the State of Washington, United States?",
    correctAnswer: "Olympia",
    incorrectAnswers: ["Washington D.C.", "Seattle", "Yukon"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "Which of the following is NOT a capital city?",
    correctAnswer: "Sydney",
    incorrectAnswers: ["Cairo", "Moscow", "Beijing"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question:
      "Gibraltar, located just south of the Iberian peninsula, is a territory of which West Europe country?",
    correctAnswer: "United Kingdom",
    incorrectAnswers: ["Spain", "Portugal", "France"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question:
      "Which European city has the highest mileage of canals in the world?",
    correctAnswer: "Birmingham",
    incorrectAnswers: ["Venice", "Amsterdam", "Berlin"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "What is the busiest port in Europe?",
    correctAnswer: "Port of Rotterdam",
    incorrectAnswers: [
      "Port of Antwerp",
      "Port of Hamburg",
      "Port of Amsterdam",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question:
      "What&#039;s the first National Park designated in the United States?",
    correctAnswer: "Yellowstone",
    incorrectAnswers: ["Sequoia ", "Yosemite", "Rocky Mountain"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "On a London Underground map, what colour is the Circle Line?",
    correctAnswer: "Yellow",
    incorrectAnswers: ["Red", "Blue", "Green"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[1].id,
    categoryId: categories[2].id,
    question: "Which German city is located on the River Isar?",
    correctAnswer: "Munich",
    incorrectAnswers: ["Berlin", "Hamburg", "Dortmund"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question:
      "The Andaman and Nicobar Islands in South East Asia are controlled by which country?",
    correctAnswer: "India",
    incorrectAnswers: ["Vietnam", "Thailand", "Indonesia"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "What is the capital of Wisconsin, USA?",
    correctAnswer: "Madison",
    incorrectAnswers: ["Milwaukee", "Wisconsin Dells", "Green Bay"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question:
      "Where is the fast food chain &quot;Panda Express&quot; headquartered?",
    correctAnswer: "Rosemead, California",
    incorrectAnswers: [
      "Sacramento, California",
      "Fresno, California",
      "San Diego, California",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "What is the most populous Muslim-majority nation in 2010?",
    correctAnswer: "Indonesia",
    incorrectAnswers: ["Saudi Arabia", "Iran", "Sudan"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "What is the capital of Mauritius?",
    correctAnswer: "Port Louis",
    incorrectAnswers: ["Port Moresby", "Port Vila", "Port-au-Prince"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "What is the second-largest city in Lithuania?",
    correctAnswer: "Kaunas",
    incorrectAnswers: ["Panevėžys", "Vilnius", "Klaipėda"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "Which of these is NOT a city in India?",
    correctAnswer: "Islamabad",
    incorrectAnswers: ["Hyderabad", "Ahmedabad", "Ghaziabad"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "Which country was NOT formerly part of Yugoslavia?",
    correctAnswer: "Albania",
    incorrectAnswers: ["Croatia", "Serbia", "Macedonia"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "Which of these is NOT a real tectonic plate?",
    correctAnswer: "Atlantic Plate",
    incorrectAnswers: ["North American Plate", "Eurasian Plate", "Nazca Plate"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "What is the Finnish word for &quot;Finland&quot;?",
    correctAnswer: "Suomi",
    incorrectAnswers: ["Eesti", "Magyarorsz&aacute;g", "Sverige"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "What national museum will you find in Cooperstown, New York?",
    correctAnswer: "National Baseball Hall of Fame",
    incorrectAnswers: [
      "Metropolitan Museum of Art",
      "National Toy Hall of Fame",
      "Museum of Modern Art",
    ],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question:
      "The Maluku islands (informally known as the Spice Islands) belong to which country?",
    correctAnswer: "Indonesia",
    incorrectAnswers: ["Chile", "New Zealand", "Fiji"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "The Hunua Ranges is located in...",
    correctAnswer: "New Zealand",
    incorrectAnswers: ["Nepal", "China", "Mexico"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question:
      "What is the name of the formerly rich fishing grounds off the island of Newfoundland, Canada?",
    correctAnswer: "Grand Banks",
    incorrectAnswers: ["Great Barrier Reef", "Mariana Trench", "Hudson Bay"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "Which is not a country in Africa?",
    correctAnswer: "Guyana",
    incorrectAnswers: ["Senegal", "Liberia", "Somalia"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "What year is on the flag of the US state Wisconsin?",
    correctAnswer: "1848",
    incorrectAnswers: ["1634", "1783", "1901"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question:
      "The emblem on the flag of the Republic of Tajikistan features a sunrise over mountains below what symbol?",
    correctAnswer: "Crown",
    incorrectAnswers: ["Bird", "Sickle", "Tree"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "Which of these cities is NOT in England?",
    correctAnswer: "Edinburgh",
    incorrectAnswers: ["Oxford", "Manchester", "Southampton"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "Fucking is a village in which country?",
    correctAnswer: "Austria",
    incorrectAnswers: ["Germany", "Switzerland", "Czech Republic"],
  },
  {
    id: uuidv4(),
    type: "multiple",
    difficultyId: difficulties[2].id,
    categoryId: categories[2].id,
    question: "What is the official German name of the Swiss Federal Railways?",
    correctAnswer: "Schweizerische Bundesbahnen",
    incorrectAnswers: [
      "Schweizerische Nationalbahnen",
      "Bundesbahnen der Schweiz",
      "Schweizerische Staatsbahnen",
    ],
  },
];
module.exports = { difficulties, questions, categories };
